[True,
	[
		["Field items",0,
			[
				["Land_BagFence_Short_F",1],
				["Land_BagFence_Long_F",2],
				["Land_BagFence_Round_F",2],
				["Land_BagFence_01_short_green_F",1],
				["Land_BagFence_01_long_green_F",2],
				["Land_BagFence_01_round_green_F",2],
				["FlagCarrierSmall",0],
				["Land_Plank_01_4m_F",1],
				["Land_Plank_01_8m_F",2],
				["Land_prebehlavka",3]
			]
		],
		["Camo nets",1,
			[
				["Land_CamoNetB_NATO_EP1",5],
				["Land_CamoNetVar_NATO_EP1",2],
				["Land_CamoNet_NATO_EP1",2],
				["Land_CamoNetB_EAST_EP1",5],
				["Land_CamoNetVar_EAST_EP1",2],
				["Land_CamoNet_EAST_EP1",2],
				["CamoNet_OPFOR_big_F",5],
				["CamoNet_OPFOR_open_F",2],
				["CamoNet_OPFOR_F",2],
				["CamoNet_wdl_big_F",5],
				["CamoNet_wdl_open_F",2],
				["CamoNet_wdl_F",2],
				["CamoNet_BLUFOR_big_F",5],
				["CamoNet_BLUFOR_open_F",2],
				["CamoNet_BLUFOR_F",2],
				["CamoNet_ghex_big_F",5],
				["CamoNet_ghex_open_F",2],
				["CamoNet_ghex_F",2],
				["CamoNet_INDP_big_F",5],
				["CamoNet_INDP_open_F",2],
				["CamoNet_INDP_F",2],
				["Land_CamoNetB_NATO",5],
				["Land_CamoNetVar_NATO",2],
				["Land_CamoNet_NATO",2],
				["NDS_6x6_ATV_camnet_cam",1],
				["NDS_6x6_ATV_camnet_des",1]
			],"\ASOT_Echo\personal_fortify\ui\CamoNet.paa"
		],
		["Sandbag Bunkers",1,
			[
				["Land_fortified_nest_small_EP1",6],
				["Land_fortified_nest_big_EP1",32],
				["Land_BagBunker_01_small_green_F",6],
				["Land_BagBunker_01_large_green_F",32]
			],"\ASOT_Echo\personal_fortify\ui\BagBunker_Small.paa"
		],
		["Obstacles",1,
			[
				["Land_DragonsTeeth_01_1x1_new_F",2],
				["Land_DragonsTeeth_01_4x2_new_F",12],
				["Wire",10],
				["Land_jezekbeton",4],
				["Land_CzechHedgehog_01_new_F",4],
				["Land_ConcreteHedgehog_01_F",4],
				["Land_Razorwire_F",4],
				["Land_Sign_MinesDanger_English_F",1]
			],"\ASOT_Echo\personal_fortify\ui\HedgeHog.paa"
		],
		["Control",1,
			[
				["Land_CncBarrier_F",4],
				["Land_CncBarrier_stripes_F",4],
				["Land_BarGate_F",2],
				["Land_HelipadSquare_F",1],
				["PortableHelipadLight_01_red_F",1],
				["Land_SignWarning_01_CheckpointAhead_F",1],
				["Land_SignM_WarningMilitaryArea_english_F",1],
				["RoadBarrier_F",1],
				["TapeSign_F",1],
				["RoadCone_L_F",0],
				["Land_Mil_WiredFence_F",2],
				["Land_Mil_WiredFence_Gate_F",1]
			],"\ASOT_Echo\personal_fortify\ui\BarGate.paa"
		],
		["Tents",1,
			[
				["Camp_EP1",5],
				["MASH_EP1",15],
				["CampEast_EP1",8],
				["CUP_A2_tent_west",8],
				["Land_tent_east",10]
			],"\ASOT_Echo\personal_fortify\ui\TentHanger.paa"
		],
		["Movement",1,
			[
				["Land_Rampart_F",20],
				["CUP_A2_Road_Bridge_wood_25",30]
			],"\ASOT_Echo\personal_fortify\ui\CanalBridge.paa"
		],
		["CBRN Decon",2,
			[
				["DeconShower_01_F",4],
				["DeconShower_02_F",16],
				["Land_WaterTank_F",2],
				["Tarp_01_Small_Black_F",1],
				["Tarp_01_Small_Yellow_F",1],
				["Tarp_01_Small_Green_F",1],
				["Tarp_01_Large_Black_F",4],
				["Tarp_01_Large_Green_F",4],
				["Tarp_01_Large_Yellow_F",4]
			]
		],
		["H-Barrier (Tan)",2,
			[
				["Land_HBarrierWall6_F",18],
				["Land_HBarrierWall4_F",12],
				["Land_HBarrierWall_corner_F",13],
				["Land_HBarrier_Big_F",10],
				["Land_HBarrier_5_F",5],
				["Land_HBarrier_3_F",3],
				["Land_HBarrier_1_F",1],
				["Land_HBarrierWall_corridor_F",16],
				["Land_HBarrierTower_F",28]
			],"\ASOT_Echo\personal_fortify\ui\HBarrierTower.paa"
		],
		["H-Barrier (Green)",2,
			[
				["Land_HBarrier_01_wall_6_green_F",18],
				["Land_HBarrier_01_wall_4_green_F",12],
				["Land_HBarrier_01_wall_corner_green_F",13],
				["Land_HBarrier_01_big_4_green_F",10],
				["Land_HBarrier_01_line_5_green_F",5],
				["Land_HBarrier_01_line_3_green_F",3],
				["Land_HBarrier_01_line_1_green_F",1],
				["Land_HBarrier_01_wall_corridor_green_F",16],
				["Land_HBarrier_01_big_tower_green_F",28]
			],"\ASOT_Echo\personal_fortify\ui\HBarrierTower.paa"
		],
		["Base",2,
			[
				["Land_Barrack2_EP1",20],
				["Land_Barrack2",20],
				["Land_MedicalTent_01_NATO_generic_open_F",10],
				["Land_MedicalTent_01_NATO_generic_outer_F",8],
				["Land_ConnectorTent_01_NATO_open_F",2],
				["Land_MedicalTent_01_NATO_tropic_generic_open_F",10],
				["Land_MedicalTent_01_NATO_tropic_generic_outer_F",8],
				["Land_ConnectorTent_01_NATO_tropic_open_F",2],
				["Land_CamoConcreteWall_01_l_4m_v1_F",5],
				["Land_CamoConcreteWall_01_pole_v1_F",1],
				["Land_Wall_IndCnc_4_F",5],
				["Land_Wall_IndCnc_Pole_F",1]
			],"\ASOT_Echo\personal_fortify\ui\HBarrierTower.paa"
		],
		["Bridge",2,
			[
				["Land_ConcretePanels_02_single_v1_F",2],
				["Land_ConcretePanels_02_four_F",6],
				["Land_RampConcrete_F",24],
				["Land_RampConcreteHigh_F",32],
				["BlockConcrete_F",24],
				["CUP_A2_Road_PMC_bridge_asf_PMC",60]
			],"\ASOT_Echo\personal_fortify\ui\RoadBridge.paa"
		],
		["CCP",2,
			[
				["TK_WarfareBFieldhHospital_Base_EP1",30],
				["US_WarfareBFieldhHospital_Base_EP1",40],
				["INS_WarfareBFieldhHospital",30],
				["USMC_WarfareBFieldhHospital",40],
				["FlagCarrierRedCross_EP1",2]
			],"z\ace\addons\medical_gui\ui\cross.paa"
		],
		["Cargo Buildings",3,
			[
				["Land_Cargo_House_V3_F",20],
				["Land_Cargo_Patrol_V3_F",30],
				["Land_Cargo_HQ_V3_F",60],
				["Land_Cargo_Tower_V3_F",100],
				["Land_Cargo_House_V1_F",20],
				["Land_Cargo_Patrol_V1_F",30],
				["Land_Cargo_HQ_V1_F",60],
				["Land_Cargo_Tower_V1_F",100]
			],"\ASOT_Echo\personal_fortify\ui\Cargo_Tower.paa"
		],
		["Concrete",3,
			[
				["Land_CncWall1_F",4],
				["Land_CncWall4_F",12],
				["Land_CncBarrierMedium_F",2],
				["Land_CncBarrierMedium4_F",6],
				["Land_CncShelter_F",2],
				["Land_Bunker_01_blocks_3_F",6],
				["Land_Bunker_01_small_F",40],
				["Land_Bunker_01_tall_F",60],
				["Land_Bunker_01_big_F",75],
				["Land_Bunker_02_light_double_F",30]
			]
		],
		["Buildings",3,
			[
				["Land_Shed_Small_F",12],
				["Land_Shed_Big_F",18],
				["Land_Barracks_02_F",25],
				["Land_Barracks_04_F",28],
				["Land_i_Barracks_V2_F",50],
				["Land_i_Barracks_V1_F",50],
				["Land_MilOffices_V1_F",40]
			],"\ASOT_Echo\personal_fortify\ui\Shed_Small.paa"
		],
		["Medical Buildings",3,
			[
				["Land_Medevac_HQ_V1_F",90],
				["Land_Medevac_house_V1_F",40],
				["Land_HelipadRescue_F",2]
			],"\ASOT_Echo\personal_fortify\ui\HelipadRescue.paa"
		],
		["Lamps",3,
			[
				["Land_PowLines_ConcL",4],
				["Land_Lampa_vysoka",6],
				["Land_Lampadrevo",6],
				["Land_LampStreet_F",7],
				["Land_Lamp_Street2_EP1",7],
				["Land_LampHalogen_F",9],
				["Land_LampAirport_F",10]
			],"\ASOT_Echo\personal_fortify\ui\PortableLight.paa"
		],
		["Heavy Bridges",3,
			[
				["Land_ConcreteBlock",24],
				["Land_ConcreteRamp",32],
				["Land_Canal_Wall_10m_F",38],
				["Land_nav_pier_m_F",144],
				["land_nav_pier_c2",288],
				["Land_Pier_F",255],
				["Land_rails_bridge_40",100]
			],"\ASOT_Echo\personal_fortify\ui\RoadBridge.paa"
		],
		["TFAR",1,
			[["TFAR_Land_Communication_F",16]]
		]
	]
, true] call perFort_fnc_registerObjectLists;